name: R-CMD-check

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r-version: ['4.3', '4.2', '4.1.1']

    steps:
      - uses: actions/checkout@v4

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R-${{ matrix.r-version }}-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-R-${{ matrix.r-version }}-

      - name: Create R library directory
        run: mkdir -p ${{ env.R_LIBS_USER }}

      - name: Install system dependencies (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc

      - name: Install Pandoc on macOS
        if: matrix.os == 'macos-latest'
        run: brew install pandoc

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install CRAN packages
        run: |
