name: R-CMD-check

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    env:
      R_LIBS_USER: ${{ github.workspace }}/R/library
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r-version: ['4.3', '4.2', '4.1.1']

    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install Pandoc on macOS
        if: runner.os == 'macOS'
        run: brew install pandoc

      - name: Install system dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install CRAN dependencies
        env:
          R_LIBS_USER: ${{ github.workspace }}/R/library
        run: |
          install.packages(c("curl", "remotes", "rcmdcheck", "testthat", "knitr", "devtools", "DT"), lib=Sys.getenv("R_LIBS_USER"))
          remotes::install_deps(dependencies = TRUE, lib=Sys.getenv("R_LIBS_USER"))
        shell: Rscript {0}

      - name: Install suggested GitHub packages
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          R_LIBS_USER: ${{ github.workspace }}/R/library
        run: |
          remotes::install_github("tkimhofer/nmrdata", lib=Sys.getenv("R_LIBS_USER"))
        shell: Rscript {0}

      - name: List installed packages
        env:
          R_LIBS_USER: ${{ github.workspace }}/R/library
        run: Rscript -e 'installed.packages(lib.loc=Sys.getenv("R_LIBS_USER"))[, "Package"]'

      - name: Run checks and tests
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
          R_LIBS_USER: ${{ github.workspace }}/R/library
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--run-donttest", "--no-build-vignettes"), error_on = "error")
          devtools::test()
        shell: Rscript {0}
